[package]
name = "genanki-rs"
version = "0.0.1"
authors = ["Yannick Funk <yannickfunk@yahoo.de>"]
edition = "2018"
description = "Rust Port of genanki"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
