name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 14 * * *'

env:
  CARGO_TERM_COLOR: always
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
        
    - name: Install Anki
      run: |
        python -m pip install --upgrade pip
        pip install anki
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --lib

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
